### ISSUE TITLE
README.md is missing

### ISSUE THREAD

**Issue by kianlavi** [jellocube/Neurorama12#1]
How am I supposed to know what Neurorama is or does without a proper README file? Also, it could use some emojis in the description 💆🏻💆🏼💆🏽💆🏿

**Comment by jellocube** [comment]
Okay, I will write a README for the next commit, including a full emoji translation.

**Comment by jellocube** [comment]
Okay, obligatory README was added, will be expanded and translated into pictograms for the public release. Thanks Kian.

**Comment by kianlavi** [comment]
👌👌🏻👌🏼👌🏽👌🏾👌🏿
